<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Password</name>
   <tag></tag>
   <elementGuidId>8ce9cfe9-3d0e-47b6-a210-6d5343eb5850</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='Login-LoginScreen-LoginDV-password']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
