<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Username</name>
   <tag></tag>
   <elementGuidId>87b76caf-56f0-4443-9081-b207fdda4ace</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='Login-LoginScreen-LoginDV-username']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
